#pragma config(Sensor, in1,    lineTracker1,   sensorLineFollower)
#pragma config(Sensor, in2,    lineTracker2,   sensorLineFollower)
#pragma config(Sensor, in3,    lineTracker3,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  lifter,         sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           elbowLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           shoulderLift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Wes Ring NextGen™ Programming
//Perry Plane III NextGen™ BaseLib

task main() //Start Kernel
{
	//Global varibles
	//enableCompetitionMode(); //Allows for compition mode
	bool isLifting = true; //checks if it is lifting
	int autoLevelPower = 20; //autoballanceing motor speed

	repeat (forever) {
		//if (getCompetitionDriverControl() == true) {}
		//Driver contols
		joystickControl(leftMotor, Ch3, 10); //Left wheel motor
		joystickControl(rightMotor, Ch2, 10); //Right wheel motor
		buttonControl(clawMotor, Btn8D, Btn8R, 70);//Claw Motor
		buttonControl(elbowLift, Btn6D, Btn5D, 70);
    buttonControl(shoulderLift,Btn6U,Btn5U,70);
	/*	if (vexRT[Btn5D] == 1) //Lifting Down
		{
			setMotor(elbowLift, 100);
		}
		else if (vexRT[Btn5U] == 1)//Lifting Up
		{
			setMotor(elbowLift, -100);
		}
		else
		{
			setMotor(elbowLift,0);
		}

		if (vexRT[Btn6D] == 1) //Lifting Up
		{
			setMotor(elbowLift, 100);
			isLifting = true;
		}
		else if (vexRT[Btn6U] == 1)//Lifting Down
		{
			setMotor(elbowLift, -100);
			isLifting = true;
		}
		else//Balance time!
		{
			if (isLifting == true){isLifting = false; SensorValue[lifter] = 0;}
			if (SensorValue[lifter] > -5){ setMotor(elbowLift, -autoLevelPower); }
			else if (SensorValue[lifter] < 5){ setMotor(elbowLift, autoLevelPower); }
			else { setMotor(elbowLift, 0); }
		}*/

		//Terminator Mode
		//if (getCompetitionAutonomous() == true) {}

	}
}
