#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightBtn,       sensorTouch)
#pragma config(Sensor, dgtl10, leftBtn,        sensorTouch)
#pragma config(Sensor, dgtl11, leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftTread,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightTread,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveInches(int inches){
	bool hasMoved = false;

	int leftTarget=41*inches;
	int rightTarget=41*inches;

	SensorValue[leftEncoder]=0;
	SensorValue[rightEncoder]=0;

	int ctr =0;

	while(hasMoved==false){

		if(SensorValue[leftEncoder]	<leftTarget){
			setMotor(leftTread,60);
		}
		else
		{
			stopMotor(leftTread);
			ctr++;
		}

		if(SensorValue[rightEncoder]	<rightTarget){
			setMotor(rightTread,50);
		}
		else
		{
			stopMotor(rightTread);
			ctr++;
		}

		if(ctr==2){
			hasMoved = true;
		}

	}
}

task main()
{
	if (SensorValue[leftBtn]==1 || SensorValue[rightBtn]==1)// satallite hit either end
	{
		moveInches(1);
	}
}
