#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           leftTread,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightTread,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
if (SensorValue[leftBtn] || SensorValue


}
