#pragma config(Sensor, dgtl1,  leftBtn,        sensorTouch)
#pragma config(Sensor, dgtl2,  rightBtn,       sensorTouch)
#pragma config(Sensor, dgtl3,  debthSonar,     sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  disEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port2,           driveMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*

  Pseudocode:
  Wait 2 seconds before program task start to allow time to be clear of the satellite after powering on the Cortex
  Wait until joystick 6U button pushed.
  Start a motor to traverse bar.
  while the touch sensor isn't pressed signifying that the satellite has not reach the end of the frame ...
    Wait for the target number of encoder counts to elapse and monitor that satellite has not reach the end of the frame.
    (2.75 in. dia, therefore 360 counts / 3.14 (2.75 in.) = 41.69 counts/in.)
    (3 in. travel = 125 counts)
    Output wheel encoder and sonar data data in streaming window for export into excel
  stop the motor
*/

task main()
{
	while(true){
		SensorValue[disEncoder]=0;        // Set optical shaft encoder quadrature count to zero
		int targetCount = 1;

		while(vexRT[Btn6U] == 0)  //Satellite waits until the button is pressed before moving on
		{
		}
		writeDebugStreamLine("New scan started");

		setMotor(driveMotor, -30);  //Turn on the motor in reverse at 64

		while(SensorValue[leftBtn] == 0) //While the final button isn't pressed...
		{

			while(abs(SensorValue[disEncoder]) < targetCount && SensorValue[leftBtn] == 0)//Wait for the encoder count to reach the target polling point (125 counts or 3 inches of travel) and satellite has not reached end of the path
			{
			}
			writeDebugStreamLine("%d \t %d", SensorValue(disEncoder), SensorValue(debthSonar));  //...and then write optical shaft encoder and sonar values to the debug stream
			targetCount = targetCount + 41; // Sensor data is written every 125 counts or 3 inches of travel
		}

		stopMotor(driveMotor); //Stop the motor
		writeDebugStreamLine("Scan ended");

		//returing to starting position
		int oldCount = SensorValue(disEncoder)-25;//-25 to account for inertia when stopping
		SensorValue[disEncoder]=0;        // Set optical shaft encoder quadrature count to zero
		setMotor(driveMotor, 60);
		while(abs(SensorValue[disEncoder]) < oldCount )
		{
		}
		stopMotor(driveMotor);

	}
}   // End task main
