#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Project Gravenstein
* Wes Ring
*/

void roboControl(void){ //For autonomous control

}

void manualControl(void){ //For manual control
	if (abs(vexRT(Ch2)) > 5 || abs(vexRT(Ch3)) > 5){
		motor[leftMotor] = vexRT(Ch3);
		motor[rightMotor] = vexRT(Ch2);
	}
	else
	{
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
	}
}

task main(){
	enableCompetitionMode(); //This makes it so the Vex Competition machine can take control
	bool _CompetitionMode = true; //Allowing us to refrence if we are in Competition Mode
	repeat(forever){
		if (_CompetitionMode == true){
			if (getCompetitionDriverControl() == true) {manualControl();} //Driver Controls
			if (getCompetitionAutonomous() == true) {roboControl();} //Robo Controls
		} else {
		manualControl(); //For driver controls
		//roboControl();// For robo controls
		}

	}
}
