#pragma config(Sensor, in1,    launcherDegree, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encoder_Left,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoder_Right,  sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           launcherMotors, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           hozBelt,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           vertBelt,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Project Gravenstein
* By Wes Ring©
* Riley Schoppa©
*/

int launcherSpeed = 0;
int launcherSpeed_new = 0;
int autoSpeed = 127;
bool hozBelt_on = false;
bool hozBeltBtn_beenPressed = false;

void setLauncherSpeed(int _speed){ //Sets the launcher speed
	setMotor(launcherMotors, _speed);
}

void stopLauncher(void){ //Kills the launcher
	stopMotor(launcherMotors);
	launcherSpeed = 0;
	launcherSpeed_new = 0;
}

void updateLauncherSpeed(void){ //Updates the launcher speed changes
	if (launcherSpeed < launcherSpeed_new){launcherSpeed++;wait(.1);}
	if (launcherSpeed > launcherSpeed_new){launcherSpeed--;wait(.1);}
	setLauncherSpeed(launcherSpeed);
}

void goForwardFor_time(int time){ //Goes forward for a set ammount of time
	setMotor(leftMotor,autoSpeed);//Use -8 to go forward
	setMotor(rightMotor,(autoSpeed-5));
	clearTimer(T1);
	while(time1[T1] < time* 1000){updateLauncherSpeed();setMotor(hozBelt,100);}
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}
void goForwardFor_time_escape(int time){ //Goes forward for a set ammount of time
	setMotor(leftMotor,autoSpeed);//Use -8 to go forward
	setMotor(rightMotor,(autoSpeed-5));
	clearTimer(T1);
	while(time1[T1] < time* 1000 && !vexRT(Btn8U)){updateLauncherSpeed();setMotor(hozBelt,100);}
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}
void goBackwardFor_time(int time){ //Goes Backwards for a set ammount of time
	setMotor(leftMotor,-autoSpeed);
	setMotor(rightMotor,-autoSpeed);
	clearTimer(T1);
	while(time1[T1] < time* 1000){updateLauncherSpeed();}
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}
void goForwardFor_distance(int targetInches){//Go Forwards a distance
	//600  = 13.5in (44.444)perIn
	//600 -right, +left
	int targetDistance = targetInches * (44.4);
	SensorValue(encoder_Left) = 0;
	while(encoder_Left < targetDistance){
		//Change left motor
		if (encoder_Left < targetDistance-30) {setMotor(leftMotor,autoSpeed);setMotor(rightMotor,autoSpeed);}
		else if (encoder_Left > targetDistance+30) {setMotor(leftMotor,-autoSpeed);setMotor(rightMotor,-autoSpeed);}
		else {stopMotor(leftMotor);stopMotor(rightMotor);}
		updateLauncherSpeed();//Check for changes
	}
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}
void goBackwardFor_distance(int targetInches){//Go backwards a distance
	//600  = 13.5in (44.444)perIn
	//600 -right, +left
	int targetDistance = targetInches * (44.4) * -1;
	SensorValue(encoder_Left) = 0;
	while(encoder_Left > targetDistance){
		//Change left motor
		if (encoder_Left > targetDistance+30) {setMotor(leftMotor,-autoSpeed);setMotor(rightMotor,-autoSpeed);}
		else if (encoder_Left < targetDistance-30) {setMotor(leftMotor,autoSpeed);setMotor(rightMotor,autoSpeed);}
		else {stopMotor(leftMotor);stopMotor(rightMotor);}
		updateLauncherSpeed();//Check for changes
	}
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}
void safeLauncherStop(void){
	launcherSpeed_new = 0; //Set our new target speed
	if(launcherSpeed > 22){launcherSpeed = launcherSpeed - 22;} //Do our first drop down, so it dosn't take so long
	else {launcherSpeed = 0;}
}

/*	 ----------------------------		Main Loops  -------------------------------		*/

void roboControl(void){ //For autonomous control	//This is test code
	setLauncherSpeed(30);
	launcherSpeed_new = 120;//Lets start this
	goForwardFor_time(5.3);//Go forward 11 seconds
	clearTimer(T1);
	while(time1[T1] < 20000){setMotor(vertBelt,100);setMotor(hozBelt,100);}
}

void manualControl(void){ //For manual control

	if (abs(vexRT(Ch2)) > 15 || abs(vexRT(Ch3)) > 15){ //Only move if we pop over 15 units on the controls
		//Run the motors at the joystick input
		setMotor(leftMotor,vexRT(Ch2));
		setMotor(rightMotor,vexRT(Ch3));
		}	else {
		//Kill the motors
		stopMotor(leftMotor);
		stopMotor(rightMotor);
	}

	if (vexRT(Btn8U)){//If 8D is pressed, launch the macro
		setLauncherSpeed(30);
		launcherSpeed_new = 120;//Lets start this
		goForwardFor_time_escape(5.3);//Go forward 11 seconds
		clearTimer(T1);
		while(time1[T1] < 20000){setMotor(vertBelt,100);setMotor(hozBelt,100);}
	}


	// Starts and stops the horizontal belt
	if (vexRT(Btn8L)){hozBeltBtn_beenPressed = true;} //We have pressed it
	if (!vexRT(Btn8L) && hozBeltBtn_beenPressed){ //When we let go lets flip
		if (!hozBelt_on){hozBelt_on = true; setMotor(hozBelt,100);}else{hozBelt_on = false;stopMotor(hozBelt);}
		hozBeltBtn_beenPressed = false;
	}

	if (vexRT(Btn5D)||vexRT(Btn6D)){ // Starts and stops verticle belt
		if (vexRT(Btn5D)){setMotor(vertBelt,-100);} else {setMotor(vertBelt,100);}
		} else {
		stopMotor(vertBelt);
	}

	/*			Launcher speeds			*/
	if (vexRT(Btn8R)){ stopLauncher();} //Emergency launcher Stop
	if (vexRT(Btn7D)){ safeLauncherStop();} //Safe launcher Stop
	if (vexRT(Btn7L)){ launcherSpeed_new = 65;} //Sets launcher speed to 65
	if (vexRT(Btn7U)){ launcherSpeed_new = 100;} //Sets launcher speed to 100
	if (vexRT(Btn7R)){ launcherSpeed_new = 127;} //Sets launcher speed to 127 (max)
	updateLauncherSpeed();
}

task main(){
	enableCompetitionMode(); //This makes it so the Vex Competition machine can take control
	repeat(forever){
		if (getCompetitionAutonomous() == true) {roboControl();} //Competition robo Controls
		if (getCompetitionDriverControl() == true) {manualControl();} //Competition driver Controls
	}
}
