#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Project Gravenstein
* Wes Ring
* DDDDDDADADADADADADADADADADADA ANNANANANANANANANNANANAN
*/

void roboControl(void){ //For autonomous control

}

void manualControl(void){ //For manual control
	if (abs(vexRT(Ch2)) > 5 || abs(vexRT(Ch3)) > 5){ //Only move if we pop over 5 units on the controls
		//Run the motors at the joystick input
		setMotor(leftMotor,vexRT(Ch3));
		setMotor(rightMotor,vexRT(Ch2));
	}
	else
	{
		//Kill the motors
		stopMotor(leftMotor);
		stopMotor(rightMotor);
	}
}

task main(){
	enableCompetitionMode(); //This makes it so the Vex Competition machine can take control
	bool _CompetitionMode = true; //Allowing us to refrence if we are in Competition Mode

	repeat(forever){
		if ( _CompetitionMode == true){
			if (getCompetitionDriverControl() == true) {manualControl();} //Competition driver Controls
			if (getCompetitionAutonomous() == true) {roboControl();} //Competition robo Controls
		} else {
		manualControl(); //For driver controls
		//roboControl();// For robo controls
		}
	}
}
