#pragma config(Motor,  port1,           leftMotor2,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           hozBelt,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           vertBelt,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           launcherMotorLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           launcherMotorRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor2,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* Project Gravenstein
* By Wes Ring©
* Riley Schoppa©
*/

int launcherSpeed = 0;
int launcherSpeed_new = 0;
int autoSpeed = 127;

void setLeftMotors(int _speed){
	setMotor(leftMotor,_speed);
	setMotor(leftMotor2,_speed);
}

void setRightMotors(int _speed){
	setMotor(rightMotor,_speed);
	setMotor(rightMotor2,_speed);
}

void stopLeftMotors(void){
	stopMotor(leftMotor);
	stopMotor(leftMotor2);
}
void stopRightMotors(void){
	stopMotor(rightMotor);
	stopMotor(rightMotor2);
}

void setLauncherSpeed(int _speed){ //Sets the launcher speed
	setMotor(launcherMotorLeft, _speed);
	setMotor(launcherMotorRight, _speed);
}
void stopLauncher(void){ //Kills the launcher
	stopMotor(launcherMotorLeft);
	stopMotor(launcherMotorRight);
	launcherSpeed = 0;
	launcherSpeed_new = 0;
}
void safeLauncherStop(void){
	launcherSpeed_new = 0; //Set our new target speed
	if(launcherSpeed > 22){launcherSpeed = launcherSpeed - 22;} //Do our first drop down, so it dosn't take so long
	else {launcherSpeed = 0;}
}
void updateLauncherSpeed(void){ //Updates the launcher speed changes
	if (launcherSpeed < launcherSpeed_new){launcherSpeed++;wait(.1);}
	if (launcherSpeed > launcherSpeed_new){launcherSpeed--;wait(.1);}
	setLauncherSpeed(launcherSpeed);
}
void updateLauncherSpeed(int inc){ //Updates the launcher speed changes
	if (launcherSpeed < launcherSpeed_new){launcherSpeed+=inc;wait(.1);}
	if (launcherSpeed > launcherSpeed_new){launcherSpeed--;wait(.1);}
	setLauncherSpeed(launcherSpeed);
}
void launcherSpeedHop(void){
	int speedHop = 15;
	if (launcherSpeed < speedHop){
		setLauncherSpeed(launcherSpeed+speedHop);
	}
}

void goForwardFor_time(int time){ //Goes forward for a set ammount of time
	setMotor(leftMotor,autoSpeed-8);
	setMotor(leftMotor2,autoSpeed-8);
	setMotor(rightMotor,autoSpeed);
	setMotor(rightMotor2,autoSpeed);//Use -8 to go forward
	clearTimer(T1);
	while(time1[T1] < time* 1000){updateLauncherSpeed();setMotor(hozBelt,100);}
	stopRightMotors();
	stopLeftMotors();
}
void goBackwardFor_time(int time){ //Goes Backwards for a set ammount of time
	setMotor(leftMotor,-autoSpeed-8);
	setMotor(leftMotor2,-autoSpeed-8);
	setMotor(rightMotor,-autoSpeed);
	setMotor(rightMotor2,-autoSpeed);//Use -8 to go forward
	clearTimer(T1);
	while(time1[T1] < time* 1000){updateLauncherSpeed();}
	stopLeftMotors();
	stopRightMotors();
}

void turnRight(int time){
	setMotor(leftMotor,autoSpeed);
	setMotor(leftMotor2,autoSpeed);
	clearTimer(T1);
	while(time1[T1] < time * 1000){updateLauncherSpeed();}
	stopLeftMotors();
	stopRightMotors();
}
/*	 ----------------------------		Main Loops  -------------------------------		*/

void roboControl(void){ //For autonomous control
	setLauncherSpeed(30);
	launcherSpeed_new = 90;//Lets start this shoot speed
	goForwardFor_time(11);//Go forward 10 seconds
	clearTimer(T1);
	while(time1[T1] < 15000){setMotor(vertBelt,80);setMotor(hozBelt,100);updateLauncherSpeed(2);}
	goBackwardFor_time(1);
	turnRight(1.5);
	goForwardFor_time(.5);
	turnRight(.7);
	goForwardFor_time(5);
}

void manualControl(void){ //For manual control

	if (abs(vexRT(Ch2)) > 15 || abs(vexRT(Ch3)) > 15){ //Only move if we pop over 15 units on the controls
		//Run the motors at the joystick input
		setLeftMotors(vexRT(Ch2));
		setRightMotors(vexRT(Ch3));
		}	else {
		//Kill the motors
		stopLeftMotors();
		stopRightMotors();
	}

	// Starts and stops verticle belt
	if (vexRT(Btn5D)||vexRT(Btn6D)){
		if (vexRT(Btn5D)){setMotor(vertBelt,-100);} else {setMotor(vertBelt,100);}
	}

	// Starts and stops verticle belt
	if (vexRT(Btn5U)||vexRT(Btn6U)){
		if (vexRT(Btn5U)){setMotor(hozBelt,-100);} else {setMotor(hozBelt,100);}
	}

	//Kill the belts
	if (vexRT(Btn8D)){stopMotor(hozBelt);stopMotor(vertBelt);}

	// Starts and stops the horizontal belt
	/*
	if (vexRT(Btn8L)){hozBeltBtn_beenPressed = true;} //We have pressed it
	if (!vexRT(Btn8L) && hozBeltBtn_beenPressed){ //When we let go lets flip
	if (!hozBelt_on){hozBelt_on = true; setMotor(hozBelt,100);}else{hozBelt_on = false;stopMotor(hozBelt);}
	hozBeltBtn_beenPressed = false;
	}
	*/

	//Quick start, all on
	if (vexRT(Btn7L)){
		setMotor(hozBelt,100);
		setMotor(vertBelt,100);
		launcherSpeed_new = 127;
	}

	/*			Launcher speeds			*/
	if (vexRT(Btn7D)){ stopLauncher();} //Emergency launcher Stop
	//if (vexRT(Btn7D)){ safeLauncherStop();} //Safe launcher Stop
	if (vexRT(Btn7R)){launcherSpeed_new = 75;}//Low speed mode
	if (vexRT(Btn7U)){ launcherSpeed_new = 127;} //Sets launcher speed to 127 (max)
	updateLauncherSpeed();
}

task main(){
	enableCompetitionMode(); //This makes it so the Vex Competition machine can take control
	repeat(forever){
		if (getCompetitionAutonomous() == true) {roboControl();} //Competition robo Controls
		if (getCompetitionDriverControl() == true) {manualControl();} //Competition driver Controls
	}
}
