#pragma config(Sensor, in1,    LightValue,     sensorReflection)
#pragma config(Sensor, dgtl1,  EncoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderRight,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  SonarFront,     sensorSONAR_inch)
#pragma config(Sensor, dgtl7,  SonarBack,      sensorSONAR_inch)
#pragma config(Motor,  port1,           Left,          tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           FlashLight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port10,          Right,         tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project TankBot
*/
void autoHeadLight (void)
{
	if (SensorValue(LightValue) > 300)
	{
		turnFlashlightOn(FlashLight,127);
	}
	else
	{
		turnFlashlightOff(FlashLight);
	}
}

void tankForwardRotations (int rotations)
{
	SensorValue(EncoderLeft) = 0;
	SensorValue(EncoderRight) = 0;
	while(SensorValue(EncoderLeft) < (rotations*360)){
		startMotor(Left, 75);
		startMotor(Right,75);
	}
	stopMotor(Right);
	stopMotor(Left);
}

void tankForwardDistance (int Distance)
{
	while(abs(SensorValue(SonarFront)) > Distance){
		startMotor(Left, 75);
		startMotor(Right,75);
		autoHeadLight();
	}
	stopMotor(Right);
	stopMotor(Left);
}

void tankBackwardDistance (int Distance)
{
	while(abs(SensorValue(SonarBack)) > Distance){
		startMotor(Left, -75);
		startMotor(Right,-75);
		autoHeadLight();
	}
	stopMotor(Right);
	stopMotor(Left);
}

void tankTurnRotations (int rotations, bool isLeft)
{
	SensorValue(EncoderLeft) = 0;
	SensorValue(EncoderRight) = 0;
	while(abs(SensorValue(EncoderLeft)) < (rotations*360)){
		startMotor(Left, -75);
		startMotor(Right,75);
	}
	stopMotor(Right);
	stopMotor(Left);
}

void tankTurn (bool isLeft)
{
	SensorValue(EncoderLeft) = 0;
	SensorValue(EncoderRight) = 0;
	while(abs(SensorValue(EncoderLeft)) < (2*280)){
		startMotor(Left, -75);
		startMotor(Right,75);
	}
	stopMotor(Right);
	stopMotor(Left);
}

void manualControl (void)
{
	if (abs(vexRT(Ch2)) > 5 || abs(vexRT(Ch3)) > 5){
		startMotor(Left,vexRT(Ch3));
		startMotor(Right,vexRT(Ch2));
	}
	else
	{
		stopMotor(Right);
		stopMotor(Left);
	}
	if (vexRT(Btn6U) == 1)
	{turnFlashlightOn(FlashLight);}
	else {turnFlashlightOff(FlashLight);}
}

task main()
{
	repeat(forever){
		manualControl();
		if (vexRT(Btn7U) == 1){
			tankForwardRotations(31); //forward 16 feet
			wait(5); //Wait 15 sec
			tankTurn(true);//Turn Left
			tankForwardDistance(7); //Go forwards tell 8 inches
			wait(5); //Wait 30
			tankBackwardDistance(2); //Go backwards tell 2 inches
		}
	}
}
